### ISSUE TITLE
Updating incorrect Ingress annotation value does not update Gslb

### ISSUE THREAD

**Issue by donovanmuller** [k8gb-io/k8gb#1765]
K8gb version: `0.14.0`

Using [Ingress annotations](https://www.k8gb.io/docs/ingress_annotations.html) and initially providing an _invalid_ value for `k8gb.io/strategy` for example:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/target-type: ip
    k8gb.io/primary-geotag: eu
    k8gb.io/strategy: round-robin # incorrect
...
```

will result in a new implicit `Gslb` resource with the incorrect value. Controller logs show the expected error:

```
2024-10-28T19:31:29Z ERR github.com/k8gb-io/k8gb/controllers/logging/logr.go:72 > events: Reconciler error {"Gslb":"test/xxx","controller":"gslb","controllerGroup":"k8gb.absa.oss","controllerKind":"Gslb","name":"xxx","namespace":"test","reconcileID":"59640c10-7eb4-4ed7-bc6b-f9ff18f91b28"} error="resolving spec ('Type' must be one of the values [roundRobin geoip failover])"
```

However, adjusting the incorrect `k8gb.io/strategy` value to `roundRobin` does not update the `Gslb` resource.

**Comment by abaguas** [comment]
Would you be able to migrate to the new `refResolver` structure?
That would help simplifying the codebase since we would not have to watch any resources besides the GSLB.

```
apiVersion: k8gb.absa.oss/v1beta1
kind: Gslb
metadata:
  name: test-gslb-failover
  namespace: test-gslb
spec:
  resourceRef:
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    matchLabels:
      app: test-gslb-failover
  strategy:
    type: failover
    primaryGeoTag: eu-west-1
```
