### ISSUE TITLE
[openshift-support] k8gb does not have the permissions to set the ingress name

### ISSUE THREAD

**Issue by raffaelespazzoli** [k8gb-io/k8gb#422]
the k8gb pod reports this error:
```
{"@l":"error","error":"ingresses.extensions \"roundrobin\" is invalid: spec.rules[0]: Forbidden: you do not have permission to set host fields in ingress rules","@c":"/home/runner/work/k8gb/k8gb/controllers/ingress.go:69","@t":1617380503,"@m":"Failed to create new Ingress Ingress.Namespace: k8gb-test, Ingress.Name: roundrobin"}
```
in order to fix this error the following permissions must be granted:
```
- apiGroups:
  - route.openshift.io
  resources:
  - routes/custom-host
  verbs:
  - create
  - update
  ```
  it should be possible to safely grant this permissions always as it does not do anything when not running in openshift.
