### ISSUE TITLE
core dns load balancer does not get the correct targetPort

### ISSUE THREAD

**Issue by raffaelespazzoli** [k8gb-io/k8gb#423]
the loadbalancer service deployed by setting the option:
```
exposeCoreDNS: true
```
is configured with the target port statically set to 53.
In some systems this requires privileges permissions, so user will change this to a different port via the following config:
```
coredns:
  servers:
    - zone: .
    port: 5353
```
the load balancer service template be changed to pick this setting.
