### ISSUE TITLE
Helm chart produces empty lines in yamls

### ISSUE THREAD

**Issue by jkremser** [k8gb-io/k8gb#631]
When using `helm template ... chart/k8gb` the resulting list of yamls contains couple of empty lines. It's more an aesthetic thing, because semantically it's a valid format, but still. It's caused by the helm chart conditions and that missing dash symbols.

example:

```yaml
...
template:
    metadata:
      labels:
        name: k8gb
    spec:

      serviceAccountName: k8gb
      containers:
        - name: k8gb
          ...
          env:
              ...
            - name: DNS_ZONE
              value: cloud.example.com
            - name: RECONCILE_REQUEUE_SECONDS
              value: "30"




            - name: LOG_FORMAT
              value: "simple"
            - name: LOG_LEVEL
              value: "info"
            - name: NO_COLOR
              value: "true"
              ...
```
