### ISSUE TITLE
[BUG] GSLB is not updated when Ingress has change

### ISSUE THREAD

**Issue by kuritka** [k8gb-io/k8gb#932]
We found a bug where GSLB does not update itself (specifically annotations section) when the ingress has changed. 

The problem with the annotations was that the rancher kept changing the annotations and k8gb kept changing them back. They were stuck in a loop.

The bug is located here: https://github.com/k8gb-io/k8gb/blob/8820bba2d07a9c13c233e725c17cf06e4aeaf696/controllers/gslb_controller.go#L234-L237

 - implement an update functionality of the GSLB as the ingress changes.
 - Implement the necessary tests to make sure that the GSLB update is done exactly as we need.

**Comment by kuritka** [comment]
returning back on this task:

### BUG replication manually
 having ONLY simple podinfo app and k8gb deployed (using clean test environment https://github.com/kuritka/k8gb-demo-cncf-2022)
 
than, by applying ingress puting test application under k8gb control (application is loadbalancable):
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    x.y.io/ep: '[{"addresses":["1.2.3.4"],"port":80}]'
    k8gb.io/strategy: roundRobin
  name: gslb
  namespace: demo
spec:
  ingressClassName: nginx
  rules:
  - host: demo.cloud.example.com
    http:
      paths:
      - backend:
          service:
            name: frontend-podinfo
            port:
              name: http
        path: /
        pathType: Prefix
```

manually changing  ingress `k  -n demo edit ing gslb` and change annotation to `x.y.io/ep: '[{"addresses":["2.2.2.2"],"port":8080}]'`

command `k -n demo get ing -o=jsonpath='{.items[*].metadata.annotations}{"\n"}'` returns unchanged annotation 
`map[x.y.io/ep:[{"addresses":["1.2.3.4"],"port":80}] `
